# Generated by Django 3.2.4 on 2021-06-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healing_chakra_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('mobile', models.TextField(blank=True, null=True)),
                ('aadhaar', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('medicine_name', models.TextField(blank=True, null=True)),
                ('manufacture_date', models.TextField(blank=True, null=True)),
                ('expiry_date', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
