# Generated by Django 3.2.4 on 2021-06-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healing_chakra_app', '0003_equipmentdonation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentdonation',
            old_name='medicine_name',
            new_name='equipment_name',
        ),
    ]
